---
name: Continuous Integration (custom fonts only)

'on':
  workflow_dispatch: {}
  pull_request: {}
  push:
    paths:
      - .github/workflows/iosevka.yml
      - roles/iosevka/**

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  run-playbook:
    name: Run playbook
    runs-on: macos-latest
    env:
      ANSIBLE_FORCE_COLOR: '1'
      ANSIBLE_CONFIG: ci/ansible.cfg
    steps:
      - name: Check out sources
        uses: actions/checkout@v4

      - name: Run playbook (first run)
        run: ./install.sh -t dotfiles,nvm,iosevka --extra-vars '@ci/config_overrides.yml' --extra-vars iosevka_enabled=true

      - name: Run playbook (second run)
        run: ./install.sh -t dotfiles,nvm,iosevka --extra-vars '@ci/config_overrides.yml' --extra-vars iosevka_enabled=true | tee /tmp/secondrun.log

      - name: Upload second run output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: second-run-output
          path: /tmp/secondrun.log

  idempotence:
    name: Check idempotence
    runs-on: ubuntu-latest
    needs: run-playbook
    steps:
      - name: Download second run output artifact
        uses: actions/download-artifact@v4
        with:
          name: second-run-output

      - name: Check idempotence
        run: >-
          grep -A1 -e 'PLAY RECAP' secondrun.log| grep -q -e 'changed=0.*failed=0'
          && (echo 'Idempotence test: pass' && exit 0)
          || (echo 'Idempotence test: fail' && exit 1)
